# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-08 06:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serv', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serv',
            name='id',
        ),
        migrations.AddField(
            model_name='serv',
            name='rpass',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='serv',
            name='ip',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
